### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by ozboss** [marduklev/skin.titan.mod.beta.leia#1]
There seems to be some kind of bug:
I'm using the "Netflix bingie mode" and have "Show all widgets" disabled.
Now when I click on a category like "Add-on browser" with no widgets in it and go back, i can't scroll up and down anymore.
To bypass this I always click "s" twice to pop up the settings menu, then it works again....

**Comment by marduklev** [comment]
@ozboss I will take a look for a fix next time. ;-)

**Comment by marduklev** [comment]
@ozboss , can you confirm, the fix? if so i will close this issue, 
EDIT: may i forget to mention, default setting when home main menu item has focus and you click back, you will focus the "bottom menu group" (settings/exit)", click back from there will focus main menu group

**Comment by ozboss** [comment]
Thanks for the fast response.
Well i may have been describing my problem wrong. Navigation with the back command (backspace) works fine.

I was navigating with the arrow keys and it works like this:
When I go into a home menu item like "Movies" I can press right and the submenu opens.
When I click right again, I get to my widgets.
From there I can click left and get back to "Movies" in the main menu.

But the problem is that the same doesn't work with a home menu item like "Addon-Browser" where there are no widgets.
I still can click right twice and get to where the widgets would be, but i can't go back by clicking left.
(At least with the settings described above)

As I'm currently setting up a lot of stuff I'm ending up in this screen quite often and never could go back without pressing the "S" or "M" key, I wasn't thinking about pressing backspace though or it just works since your fix idk :D

**Comment by marduklev** [comment]
@ozboss

Ok. So backspace was also before that fix.
Can you confirm that its also working by just using with right/left navigation!

**Comment by ozboss** [comment]
Well no sorry I installed the newest version before i wrote the comment and it's still not working.

**Comment by marduklev** [comment]
Just to be clear.Did you install from zip using

https://github.com/marduklev/skin.titan.mod.beta.leia/archive/master.zip

?

Its not in the kodi repo yet.

Edit: Now i got it. Its notworking with navigation (left), if there is an submenu and no widgets.
actual its just working if (no sub and no widgets) i take a look tomorrow again.

**Comment by ozboss** [comment]
Ok nice :)
Well I was installing the skin from the repo and it was version 18.1.8
After your comment I also installed the skin from the zip file and I got version 18.1.7 
Strange.....

**Comment by marduklev** [comment]
I just didnt update the v number in addon.xml ,so no worries.:-)

**Comment by marduklev** [comment]
hi.dont much time today, seems take a bit more time to look into that.as it is more related to the spotlight widget/buttons. I focus it next time, but it'll not be fixed till next 1 or 2 weeks . but click back is working fine.

**Comment by ozboss** [comment]
yeah now worries just wanted to let you know :) you did a great job bringing this to life on kodi 18 anyway, much appreciated

**Comment by marduklev** [comment]
ok, issue solved.

- if coming back from somwhere and no widgets are set, the main menu gets focus
- if no widgets are set for an main menu entry and click right when submenu items has focus- the main menu gets focus

**Comment by ozboss** [comment]
So I just got around to testing it and it works great :) thank you so much for the fast fix :)
