### ISSUE TITLE
Issue with View_529_NetflixSeasons

### ISSUE THREAD

**Issue by dev77-07** [marduklev/skin.titan.mod.beta.leia#14]
I'm not sure where the new view 529_nextflixseasons gets used, but using the latest version from github, I'm experiencing issues when I have a shortcut to youtube on the main menu. Opening youtube gives me an error "Mapping for path '/-1/' not found".

I've traced it to this
`<variable name="NextUp_SeasonLevel">
<value condition="String.EndsWith(Container.Folderpath,/)">$INFO[Container.Folderpath]-1/</value><value>videodb://inprogresstvshows/-1/-1/&amp;?xsp=%7B%22rules%22%3A%7B%22and%22%3A%5B%7B%22field%22%3A%22tvshow%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%5B%22$INFO[ListItem.TVShowTitle]%22%5D%7D%5D%7D%2C%22type%22%3A%22episodes%22%7D</value>
	</variable>`

I'm not using any Netflix views so I wouldn't think this would cause issues, but I guess it's being used somewhere or somehow. Not sure what the fix is, but wanted you to take a look.

**Comment by dev77-07** [comment]
Noticing another issue with this new view, even when not using it. I have shortcuts to Embycon folders on my main menu. If I go into one of those, I get the list of movies. If i go back to the main menu, it will eventually start playing the first video in the list. If i remove the view_529_netflixseasons.xml file, both my issues disappear.

**Comment by marduklev** [comment]
strange, sadly pushed to early v.1.18.5.
now less time to check.
viewtype 529 should just be used at season level
container.content(seasons)

i wondered how it affects yotube/homemenu.

will take a look soon.

**Comment by marduklev** [comment]
did a quick test.
strange
can you test 
again
pr
f7717b1fd97bdf87b2a08bee4ecfd61d42ddd743

**Comment by marduklev** [comment]
i will take a look.
really strange.
tried some things which fail.
need to look deeper.as i dont have much time in the next days, ypu should keep the file (View_529_NetflixSeasons.xml)  deleted.

and delete 
<include>
View_529_NetflixSeasons
<\>

from my videonav.xml

**Comment by marduklev** [comment]
@yeahme49 
can you report back how it behaves when exlude

`<value condition="String.EndsWith(Container.Folderpath,/)">$INFO[Container.Folderpath]-1/</value>
`
i have no idea why, but on my end it seems that its working.

**Comment by marduklev** [comment]
pushed new version.
can you report back if the issue is resolved.

**Comment by dev77-07** [comment]
Updated to latest version and it appears to be working correctly now. Thanks!
