### ISSUE TITLE
Skin not focus on Cancel button

### ISSUE THREAD

**Issue by xulek** [marduklev/skin.titan.mod.beta.leia#2]
Hello, there is a problem with skin. Skin doesn't focus on cancel button itself and there is no option to select this button without mouse. I talking about this window function "xbmcgui.DialogProgress()".

Screenshot:
https://image.ibb.co/neavcq/1.png - button not selected

Can you look on this?

**Comment by marduklev** [comment]
I take a look, does any navigation trough up,down,left,right,back working to gain the focus?

**Comment by xulek** [comment]
No, arrows don't work too to gain focus on button :(

**Comment by marduklev** [comment]
ok, last option before fix (soory not much time) , did you tried the skin setting

settings -> generel skinsetting -> "Set default Button to 'NO" in confirmation dialog" ?

**Comment by xulek** [comment]
Now with this setting works. Thank you :)

**Comment by xulek** [comment]
I have to reopen this issue :( Now with this setting skin doesn't focus when there is only one button 'ok' :/

**Comment by marduklev** [comment]
Can you report back with that change

**Comment by xulek** [comment]
seems to work well
